set runtimepath+=~/.vim_runtime

"当编辑没有权限的文件时,直接在vim里执行sudo(默认己存在Sudow)
command! -nargs=? Sudow :w !sudo tee %

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

try
source ~/.vim_runtime/my_configs.vim
catch
endtry
